#!/bin/bash
# docs/254: 取得計画。①新銘柄 bid ②既存 19 + 新銘柄の ask。9 秒/リクエスト → 合計 ≈ 18 時間。
cd /home/user/chien-monitor
NEW="EURCHF=EURCHF,GBPCHF=GBPCHF,AUDNZD=AUDNZD,AUDCAD=AUDCAD,NZDCAD=NZDCAD,CADCHF=CADCHF,USDCAD=USDCAD,XAGUSD=XAGUSD,BRENT=BRENTCMDUSD,WTI=LIGHTCMDUSD,UK100=GBRIDXGBP,JP225=JPNIDXJPY,EUSTX50=EUSIDXEUR,US30=USA30IDXUSD,AUS200=AUSIDXAUD,HK50=HKGIDXHKD,BUND=BUNDTREUR,USTBOND=USTBONDTRUSD,DXY=DOLLARIDXUSD"
OLD="EURGBP=EURGBP,USDCHF=USDCHF,NZDUSD=NZDUSD,AUDUSD=AUDUSD,CHFJPY=CHFJPY,GBPJPY=GBPJPY,EURJPY=EURJPY,AUDJPY=AUDJPY,USDJPY=USDJPY,CADJPY=CADJPY,NZDJPY=NZDJPY,EURUSD=EURUSD,GBPUSD=GBPUSD,EURAUD=EURAUD,GBPAUD=GBPAUD,XAUUSD=XAUUSD,GER40=DEUIDXEUR,NAS100=USATECHIDXUSD,US500=USA500IDXUSD"
sleep 240
python3 research/tools/dukascopy_fetch.py bid "$NEW" 2016-01 2026-08
python3 research/tools/dukascopy_fetch.py ask "$OLD" 2016-01 2026-08
python3 research/tools/dukascopy_fetch.py ask "$NEW" 2016-01 2026-08
echo "ALL DONE $(date -u)"
